---

docker_registry: "docker.io"

node_exporter_defaults:
  port: 9100
  docker:
    name: "prom/node-exporter"
    tag: "latest"

prometheus_defaults:
  port: 9090
  docker:
    name: "prom/prometheus"
    tag: "latest"

alertmanager_defaults:
  port: 9093
  docker:
    name: "prom/alertmanager"
    tag: "latest"

grafana_defaults:
  port: 3000
  docker:
    name: "grafana/grafana"
    tag: "latest"

nginx_defaults:
  listen: "0.0.0.0"
  http_port: 80
  docker:
    name: "library/nginx"
    tag: "latest"
  upstream: {}
  server_location: []
