---
roq_defaults:
  dirs:
    run: /run/roq
  systemd:
    user: ansible
    group: ansible
container_defaults:
  solution: podman
  network: roq-network
clickhouse_defaults:
  user: clickhouse
  group: clickhouse
  port: 9000
  http_port: 8123
  metrics_port: 8001
  container:
    name: clickhouse/clickhouse-server
    tag: latest
    registry: docker.io
node_exporter_defaults:
  user: root
  group: root
  port: 9100
  container:
    name: prom/node-exporter
    tag: latest
    registry: docker.io
prometheus_defaults:
  user: prometheus
  group: prometheus
  port: 9090
  container:
    name: prom/prometheus
    tag: latest
    registry: docker.io
  scrape_configs: []
alertmanager_defaults:
  user: alertmanager
  group: alertmanager
  port: 9093
  container:
    name: prom/alertmanager
    tag: latest
    registry: docker.io
grafana_defaults:
  user: grafana
  group: grafana
  port: 3000
  container:
    name: grafana/grafana
    tag: latest
    registry: docker.io
nginx_defaults:
  user: root
  group: root
  listen: 0.0.0.0
  port: 80
  container:
    name: library/nginx
    tag: latest
    registry: docker.io
