---
- name: Grafana
  tags:
    - grafana
  block:
    - name: Create user
      become: true
      ansible.builtin.user:
        name: '{{ config_grafana.user }}'
    - name: Get uid/gid
      ansible.builtin.getent:
        database: passwd
    - name: Create directories
      become: true
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: '{{ config_grafana.user }}'
        group: '{{ config_grafana.group }}'
        mode: '0755'
      with_items:
        - /usr/local/etc/grafana
        - /usr/local/etc/grafana/provisioning
        - /usr/local/etc/grafana/provisioning/dashboards
        - /usr/local/etc/grafana/provisioning/datasources
        - /var/lib/grafana
        - /var/lib/grafana/dashboards
      notify:
        - Restart grafana
    - name: Provision datasources
      become: true
      ansible.builtin.template:
        src: templates/datasources.yml
        dest: /usr/local/etc/grafana/provisioning/datasources/all.yml
        owner: '{{ config_grafana.user }}'
        group: '{{ config_grafana.group }}'
        mode: '0644'
      notify:
        - Restart grafana
    - name: Provision dashboards (common)
      become: true
      ansible.builtin.copy:
        src: files/{{ item }}
        dest: /var/lib/grafana/dashboards/{{ item }}
        owner: '{{ config_grafana.user }}'
        group: '{{ config_grafana.group }}'
        mode: '0644'
      with_items:
        - roq-dashboard.json
      notify:
        - Restart grafana
    - name: Provision dashboards
      become: true
      ansible.builtin.template:
        src: templates/dashboards.yml
        dest: /usr/local/etc/grafana/provisioning/dashboards/all.yml
        owner: '{{ config_grafana.user }}'
        group: '{{ config_grafana.group }}'
        mode: '0644'
      notify:
        - Restart grafana
    - name: Pull image
      containers.podman.podman_image:
        name: '{{ config_grafana.container.registry }}/{{ config_grafana.container.name }}'
        tag: '{{ config_grafana.container.tag }}'
        force: true
      notify:
        - Restart grafana
    - name: Create systemd service
      become: true
      ansible.builtin.template:
        src: templates/grafana.service
        dest: /etc/systemd/system/grafana.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Enable grafana
