---
- name: Config
  tags:
    - always
  block:
    - name: Create grafana config
      ansible.builtin.set_fact:
        config_grafana: >
          {{ grafana_defaults | combine(grafana | default({}), recursive=True) }}
        cacheable: true
    - name: Create prometheus config
      ansible.builtin.set_fact:
        config_prometheus: >
          {{ prometheus_defaults | combine(prometheus | default({}), recursive=True) }}
        cacheable: true
    - name: Create pushgateway config
      ansible.builtin.set_fact:
        config_pushgateway: >
          {{ pushgateway_defaults | combine(pushgateway | default({}), recursive=True) }}
        cacheable: true
