---
- name: Prometheus
  tags:
    - prometheus
  block:
    - name: Create user
      become: true
      ansible.builtin.user:
        name: '{{ config_prometheus.user }}'
    - name: Get uid/gid
      ansible.builtin.getent:
        database: passwd
    - name: Create directories
      become: true
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        owner: '{{ config_prometheus.user }}'
        group: '{{ config_prometheus.group }}'
        mode: '0755'
      with_items:
        - /var/lib/prometheus
        - /usr/local/etc/prometheus
      notify:
        - Restart prometheus
    - name: Create config files (prometheus)
      become: true
      ansible.builtin.template:
        src: templates/{{ item | basename }}
        dest: /usr/local/etc/{{ item }}
        owner: '{{ config_prometheus.user }}'
        group: '{{ config_prometheus.group }}'
        mode: '0644'
      with_items:
        - prometheus/prometheus.yml
      notify:
        - Restart prometheus
    - name: Pull image
      containers.podman.podman_image:
        name: '{{ config_prometheus.container.registry }}/{{ config_prometheus.container.name }}'
        tag: '{{ config_prometheus.container.tag }}'
        force: true
      notify:
        - Restart prometheus
    - name: Create systemd service
      become: true
      ansible.builtin.template:
        src: templates/prometheus.service
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'
      notify:
        - Enable prometheus
