---
- name: restart prometheus
  service:
    name: prometheus
    state: restarted
    enabled: true
  become: true
- name: restart node-exporter
  service:
    name: node-exporter
    state: restarted
    enabled: true
  become: true
- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted
    enabled: true
  become: true
