---
- name: Restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus.service
    state: restarted
- name: Enable prometheus
  become: true
  ansible.builtin.service:
    name: prometheus.service
    state: restarted
    enabled: true
    daemon_reload: true
